/**基础数据 url*/
export default {

	  urlBase: 'http://customer.mism.58.com',    //数据入口

	  faceBase:[                                 //输入基础表情数据
        { value: 'im-emotion-unit im-emotion-0', name: '[微笑]' },
        { value: 'im-emotion-unit im-emotion-1', name: '[撇嘴]' },
        { value: 'im-emotion-unit im-emotion-2', name: '[色]' },
        { value: 'im-emotion-unit im-emotion-3', name: '[发呆]' },
        { value: 'im-emotion-unit im-emotion-4', name: '[得意]' },
        { value: 'im-emotion-unit im-emotion-5', name: '[流泪]' },
        { value: 'im-emotion-unit im-emotion-6', name: '[害羞]' },
        { value: 'im-emotion-unit im-emotion-7', name: '[闭嘴]' },
        { value: 'im-emotion-unit im-emotion-8', name: '[睡觉]' },
        { value: 'im-emotion-unit im-emotion-9', name: '[大哭]' },
        { value: 'im-emotion-unit im-emotion-10', name: '[尴尬]' },
        { value: 'im-emotion-unit im-emotion-11', name: '[发怒]' },
        { value: 'im-emotion-unit im-emotion-12', name: '[调皮]' },
        { value: 'im-emotion-unit im-emotion-13', name: '[呲牙]' },
        { value: 'im-emotion-unit im-emotion-14', name: '[惊讶]' },
        { value: 'im-emotion-unit im-emotion-15', name: '[难过]' },
        { value: 'im-emotion-unit im-emotion-16', name: '[酷]' },
        { value: 'im-emotion-unit im-emotion-17', name: '[冷汗]' },
        { value: 'im-emotion-unit im-emotion-18', name: '[抓狂]' },
        { value: 'im-emotion-unit im-emotion-19', name: '[吐]' },
        { value: 'im-emotion-unit im-emotion-20', name: '[偷笑]' },
        { value: 'im-emotion-unit im-emotion-21', name: '[愉快]' },
        { value: 'im-emotion-unit im-emotion-22', name: '[白眼]' },
        { value: 'im-emotion-unit im-emotion-23', name: '[傲慢]' },
        { value: 'im-emotion-unit im-emotion-24', name: '[饥饿]' },
        { value: 'im-emotion-unit im-emotion-25', name: '[困]' },
        { value: 'im-emotion-unit im-emotion-26', name: '[惊恐]' },
        { value: 'im-emotion-unit im-emotion-27', name: '[流汗]' },
        { value: 'im-emotion-unit im-emotion-28', name: '[憨笑]' },
        { value: 'im-emotion-unit im-emotion-29', name: '[悠闲]' },
        { value: 'im-emotion-unit im-emotion-30', name: '[奋斗]' },
        { value: 'im-emotion-unit im-emotion-31', name: '[咒骂]' },
        { value: 'im-emotion-unit im-emotion-32', name: '[疑问]' },
        { value: 'im-emotion-unit im-emotion-33', name: '[嘘]' },
        { value: 'im-emotion-unit im-emotion-34', name: '[晕]' },
        { value: 'im-emotion-unit im-emotion-35', name: '[疯了]' },
        { value: 'im-emotion-unit im-emotion-36', name: '[衰]' },
        { value: 'im-emotion-unit im-emotion-37', name: '[骷髅]' },
        { value: 'im-emotion-unit im-emotion-38', name: '[敲打]' },
        { value: 'im-emotion-unit im-emotion-39', name: '[再见]' },
        { value: 'im-emotion-unit im-emotion-40', name: '[擦汗]' },
        { value: 'im-emotion-unit im-emotion-41', name: '[抠鼻]' },
        { value: 'im-emotion-unit im-emotion-42', name: '[鼓掌]' },
        { value: 'im-emotion-unit im-emotion-43', name: '[糗大了]' },
        { value: 'im-emotion-unit im-emotion-44', name: '[坏笑]' },
        { value: 'im-emotion-unit im-emotion-45', name: '[左哼哼]' },
        { value: 'im-emotion-unit im-emotion-46', name: '[右哼哼]' },
        { value: 'im-emotion-unit im-emotion-47', name: '[哈欠]' },
        { value: 'im-emotion-unit im-emotion-48', name: '[鄙视]' },
        { value: 'im-emotion-unit im-emotion-49', name: '[委屈]' },
        { value: 'im-emotion-unit im-emotion-50', name: '[快哭了]' },
        { value: 'im-emotion-unit im-emotion-51', name: '[阴险]' },
        { value: 'im-emotion-unit im-emotion-52', name: '[亲亲]' },
        { value: 'im-emotion-unit im-emotion-53', name: '[惊吓]' },
        { value: 'im-emotion-unit im-emotion-54', name: '[可怜]' },
        { value: 'im-emotion-unit im-emotion-55', name: '[菜刀]' },
        { value: 'im-emotion-unit im-emotion-56', name: '[西瓜]' },
        { value: 'im-emotion-unit im-emotion-57', name: '[啤酒]' },
        { value: 'im-emotion-unit im-emotion-58', name: '[篮球]' },
        { value: 'im-emotion-unit im-emotion-59', name: '[乒乓]' },
        { value: 'im-emotion-unit im-emotion-60', name: '[咖啡]' },
        { value: 'im-emotion-unit im-emotion-61', name: '[米饭]' },
        { value: 'im-emotion-unit im-emotion-62', name: '[猪头]' },
        { value: 'im-emotion-unit im-emotion-63', name: '[玫瑰]' },
        { value: 'im-emotion-unit im-emotion-64', name: '[凋谢]' },
        { value: 'im-emotion-unit im-emotion-65', name: '[示爱]' },
        { value: 'im-emotion-unit im-emotion-66', name: '[爱心]' },
        { value: 'im-emotion-unit im-emotion-67', name: '[心碎]' },
        { value: 'im-emotion-unit im-emotion-68', name: '[蛋糕]' },
        { value: 'im-emotion-unit im-emotion-69', name: '[闪电]' },
        { value: 'im-emotion-unit im-emotion-70', name: '[炸弹]' }
	  ],

	  faceShow:{                                         //展示表情数据
        '[微笑]': 'im-emotion-unit im-emotion-0',
        '[撇嘴]': 'im-emotion-unit im-emotion-1',
        '[色]': 'im-emotion-unit im-emotion-2',
        '[发呆]': 'im-emotion-unit im-emotion-3',
        '[得意]': 'im-emotion-unit im-emotion-4',
        '[流泪]': 'im-emotion-unit im-emotion-5',
        '[害羞]': 'im-emotion-unit im-emotion-6',
        '[闭嘴]': 'im-emotion-unit im-emotion-7',
        '[睡觉]': 'im-emotion-unit im-emotion-8',
        '[大哭]': 'im-emotion-unit im-emotion-9',
        '[尴尬]': 'im-emotion-unit im-emotion-10',
        '[发怒]': 'im-emotion-unit im-emotion-11',
        '[调皮]': 'im-emotion-unit im-emotion-12',
        '[呲牙]': 'im-emotion-unit im-emotion-13',
        '[惊讶]': 'im-emotion-unit im-emotion-14',
        '[难过]': 'im-emotion-unit im-emotion-15',
        '[酷]': 'im-emotion-unit im-emotion-16',
        '[冷汗]': 'im-emotion-unit im-emotion-17',
        '[抓狂]': 'im-emotion-unit im-emotion-18',
        '[吐]': 'im-emotion-unit im-emotion-19',
        '[偷笑]': 'im-emotion-unit im-emotion-20',
        '[愉快]': 'im-emotion-unit im-emotion-21',
        '[白眼]': 'im-emotion-unit im-emotion-22',
        '[傲慢]': 'im-emotion-unit im-emotion-23',
        '[饥饿]': 'im-emotion-unit im-emotion-24',
        '[困]': 'im-emotion-unit im-emotion-25',
        '[惊恐]': 'im-emotion-unit im-emotion-26',
        '[流汗]': 'im-emotion-unit im-emotion-27',
        '[憨笑]': 'im-emotion-unit im-emotion-28',
        '[悠闲]': 'im-emotion-unit im-emotion-29',
        '[奋斗]': 'im-emotion-unit im-emotion-30',
        '[咒骂]': 'im-emotion-unit im-emotion-31',
        '[疑问]': 'im-emotion-unit im-emotion-32',
        '[嘘]': 'im-emotion-unit im-emotion-33',
        '[晕]': 'im-emotion-unit im-emotion-34',
        '[疯了]': 'im-emotion-unit im-emotion-35',
        '[衰]': 'im-emotion-unit im-emotion-36',
        '[骷髅]': 'im-emotion-unit im-emotion-37',
        '[敲打]': 'im-emotion-unit im-emotion-38',
        '[再见]': 'im-emotion-unit im-emotion-39',
        '[擦汗]': 'im-emotion-unit im-emotion-40',
        '[抠鼻]': 'im-emotion-unit im-emotion-41',
        '[鼓掌]': 'im-emotion-unit im-emotion-42',
        '[糗大了]': 'im-emotion-unit im-emotion-43',
        '[坏笑]': 'im-emotion-unit im-emotion-44',
        '[左哼哼]': 'im-emotion-unit im-emotion-45',
        '[右哼哼]': 'im-emotion-unit im-emotion-46',
        '[哈欠]': 'im-emotion-unit im-emotion-47',
        '[鄙视]': 'im-emotion-unit im-emotion-48',
        '[委屈]': 'im-emotion-unit im-emotion-49',
        '[快哭了]': 'im-emotion-unit im-emotion-50',
        '[阴险]': 'im-emotion-unit im-emotion-51',
        '[亲亲]': 'im-emotion-unit im-emotion-52',
        '[惊吓]': 'im-emotion-unit im-emotion-53',
        '[可怜]': 'im-emotion-unit im-emotion-54',
        '[菜刀]': 'im-emotion-unit im-emotion-55',
        '[西瓜]': 'im-emotion-unit im-emotion-56',
        '[啤酒]': 'im-emotion-unit im-emotion-57',
        '[篮球]': 'im-emotion-unit im-emotion-58',
        '[乒乓]': 'im-emotion-unit im-emotion-59',
        '[咖啡]': 'im-emotion-unit im-emotion-60',
        '[米饭]': 'im-emotion-unit im-emotion-61',
        '[猪头]': 'im-emotion-unit im-emotion-62',
        '[玫瑰]': 'im-emotion-unit im-emotion-63',
        '[凋谢]': 'im-emotion-unit im-emotion-64',
        '[示爱]': 'im-emotion-unit im-emotion-65',
        '[爱心]': 'im-emotion-unit im-emotion-66',
        '[心碎]': 'im-emotion-unit im-emotion-67',
        '[蛋糕]': 'im-emotion-unit im-emotion-68',
        '[闪电]': 'im-emotion-unit im-emotion-69',
        '[炸弹]': 'im-emotion-unit im-emotion-70'

	  },
        //转人工提示
         tipsData:[
            '世界上有两种问题，一种是好回答的，另一种是难回答的，但这个属于好难回答……',
            '真是的，怎么能出这么难的题考人家呢，小拳拳捶你胸口～',
            '你说话的样子好可爱～让小八想一想。',
            '面对套路，沉默是金。',
            '小八在努力做一个好的聆听者。',
            '给小八一点时间，小八思考一下。',
            '貌似很有深意的样子…',
            '咦~',
            '哎，感觉自己被快要打破洪荒之力了。',
            '小八觉得您可以找人工客服啦~~',
            '哎呀，这个问题好难啊，主人要不要问一下人工客服呀~'

         ]

} 