export default {
    serverIfo:[
                {
                value:'网邻通会员都包括什么资源？'
               },
               {
                value:'58有多少推广方式？'
               },
               {
                value:'精准推广是什么？'
               },
               {
                value:'刷新点数如何使用？'
               },
               {
                value:'立即置顶/计划置顶的扣费方式？'
               },
               {
                value:'置顶手续费扣费规则？'
               },
               {
                value:'QQ推广如何付费？'
               }
            ]
  };
